### ISSUE TITLE
AttributeError: 'array.array' object has no attribute 'tostring' - issue with python version?

### ISSUE THREAD

**Issue by Strugglemeat** [pinobatch/nrom-template#2]
```
[Strugglemeat@b550maoruspro nrom-template-0.05]$ make
ca65  src/nrom.s -o obj/nes/nrom.o
ca65  src/init.s -o obj/nes/init.o
tools/pilbmp2nes.py tilesets/bggfx.png obj/nes/bggfx.chr
Traceback (most recent call last):
  File "/home/Strugglemeat/nesdev/nrom-template-0.05/tools/pilbmp2nes.py", line 210, in <module>
    main()
  File "/home/Strugglemeat/nesdev/nrom-template-0.05/tools/pilbmp2nes.py", line 187, in main
    outdata = pilbmp2chr(im, tileWidth, tileHeight,
  File "/home/Strugglemeat/nesdev/nrom-template-0.05/tools/pilbmp2nes.py", line 95, in pilbmp2chr
    data = formatTile(tile)
  File "/home/Strugglemeat/nesdev/nrom-template-0.05/tools/pilbmp2nes.py", line 188, in <lambda>
    lambda im: formatTilePlanar(im, planes, hflip, little))
  File "/home/Strugglemeat/nesdev/nrom-template-0.05/tools/pilbmp2nes.py", line 79, in formatTilePlanar
    return out.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'
make: *** [makefile:105: obj/nes/bggfx.chr] Error 1
```

sounds like tostring was changed to tobytes in later versions of python? https://github.com/python-intelhex/intelhex/issues/45

edit: yes, changing two instances of 'tostring' to 'tobytes' in the tools/pilbmp2nes.py file allowed me to run 'make'

**Comment by pinobatch** [comment]
This had been fixed in 3853039aa4
